### ISSUE TITLE
php版本能否降到 7.2 或者 7.1?

### ISSUE THREAD

**Issue by zhouyl** [overtrue/qcloud-cos-client#6]
做为公共类组件，版本要求过高会导致一些限制，可否考虑一下，降到 7.1 or 7.2

**Comment by overtrue** [comment]
PHP 7.3 仅剩 8 个月就停止安全性维护了，7.1 和 7.2 连安全性 bug 都停止维护了：https://www.php.net/supported-versions.php

还有一个问题是：从 7.0 升级到 7.4 几乎是 0 变更，为啥不升级呢？

**Comment by overtrue** [comment]
如果实在有困难没法挪出半天去升级环境，也可以有其它选择，比如官方 SDK 应该是 5.6 都可以跑。
