### ISSUE TITLE
custom domain will cause signature wrong.

### ISSUE THREAD

**Issue by branchzero** [overtrue/qcloud-cos-client#8]
When using custom domain, current signature will contain custom domain host, it will cause tencent cloud api return "403 Forbiddden".
So in Class Signature, maybe __construct should contain parameters like bucket, app_id, region, and in getHeadersToBeSigned should replace host part to prevent error, like
```
    protected static function getHeadersToBeSigned(RequestInterface $request): array
    {
        $headers = [];
        foreach ($request->getHeaders() as $header => $value) {
            $header = strtolower(urlencode($header));

            if (str_contains($header, 'x-cos-') || \in_array($header, self::SIGN_HEADERS)) {
                if ($header == 'host') {
                    $value[0] = \sprintf(
                        '%s-%s.cos.%s.myqcloud.com',
                        $this->bucket,
                        $this->app_id,
                        $this->region
                    );
                }
                $headers[$header] = $value[0];
            }
        }

        ksort($headers);

        return $headers;
    }
```

**Comment by overtrue** [comment]
@branchzero 请问你使用的自定义域名是什么样子的？

**Comment by branchzero** [comment]
随便什么自定义域名都行，默认 CDN 加速域名（xxxxxxxxxx.file.myqcloud.com）和自定义 CDN 加速域名都会触发类似的问题，因为回源地址都会被填上源站域名（xxxxx.cos.ap-xxxx.myqcloud.com），所以签名无论如何得遵循源站的host来签名。

**Comment by overtrue** [comment]
这里的域名其实不是 CDN 域名的作用，所以不能随便填的，只能填官方允许的上传域名，其实这里是为了兼容公司内的内网专用域名而设计，所以可能文档写的不是很清楚我改一下。

**Comment by overtrue** [comment]
@branchzero 目前对外应该只允许 `xxxxx.cos.ap-xxxx.myqcloud.com` 来上传，CDN 加速域名以及自定义 CDN 域名，都只有只读权限的，我先从文档上移除它。

**Comment by branchzero** [comment]
@overtrue 因为最近xxxxx.cos.ap-guangzhou.myqcloud.com被外墙了（境外访问直接reset），没办法只能套一层CDN，然后通过CDN域来解决被墙的问题，我觉得文档上其实不需要移除，说明下只允许用在**自定义源站域名**而非**默认 CDN 加速域名**、**自定义 CDN 加速域名**其实就行了。

**Comment by overtrue** [comment]
> @overtrue 因为最近xxxxx.cos.ap-guangzhou.myqcloud.com被外墙了（境外访问直接reset），没办法只能套一层CDN，然后通过CDN域来解决被墙的问题，我觉得文档上其实不需要移除，说明下只允许用在**自定义源站域名**而非**默认 CDN 加速域名**、**自定义 CDN 加速域名**其实就行了。

自定义源站域名应该也不能用来上传吧？

**Comment by overtrue** [comment]
@branchzero https://cloud.tencent.com/document/product/436/6224

**Comment by overtrue** [comment]
我再跟客服确认一下，如果自定义源站域名可以实现的话，我来加一个实现

**Comment by overtrue** [comment]
@branchzero 确认并自己测试过了，确实是可以使用自定义源站域名实现数据读写，不过我测试过程中没发现报签名错误，辛苦加一下我 Q 44294631 看看具体是哪一步出问题了。

**Comment by mouyong** [comment]
签名访问时，提示 Request has expired
